# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cathy Schmeichel
email: cat.borck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I am an illustrator, designer, cartoonist, etc. based in Milwaukee, WI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cathyschmeichel.com" # the base hostname & protocol for your site
bsky_username: catherinetheless
twitter_username: cattheless
tumblr_username: catherinetheless
instagram_username: cattheless
dribbble_username: schmeichel
location: Milwaukee, Wisconsin

# Build settings
markdown: kramdown
# gems: [bourbon, neat]
